# Generated by Django 4.1.3 on 2022-11-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khojsearch',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
